name: Build & Check

on:
  pull_request:
    types:
      - labeled
      - edited
      - synchronize
      - unlabeled
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/setup-node@v6
      - uses: actions/checkout@v6
      - run: npx -y prettier --check ./
      # Uncomment the line below to include shell script linting
      # - run: npx -y shellcheck ./.github/scripts/*.sh ./src/scripts/*.sh

  step_summary_meta:
    runs-on: ubuntu-latest
    steps:
      - run: |
          PUSH=${{ contains(github.event.pull_request.labels.*.name, 'canary') }}

          if [ "${PUSH}" = "true" ]; then
            echo "## Image Published!" >> $GITHUB_STEP_SUMMARY
            echo "> These are development images, expect bugs!!"
          fi

  build_rust:
    name: Build Rust
    uses: mbround18/gh-reusable/.github/workflows/rust-build-n-test.yaml@main
    secrets:
      DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

  build_docker:
    name: "Build Docker"
    strategy:
      fail-fast: true
      matrix:
        image: [odin, valheim]
    uses: mbround18/gh-reusable/.github/workflows/docker-release.yaml@main
    with:
      image: mbround18/${{ matrix.image }}
      target: ${{ matrix.image }}
      canary_label: canary
      dockerhub_username: mbround18
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
