name: Docker Release

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  publish:
    strategy:
      fail-fast: true
      matrix:
        image: [odin, valheim]

    uses: mbround18/gh-reusable/.github/workflows/docker-release.yaml@main
    with:
      image: mbround18/${{ matrix.image }}
      target: ${{ matrix.image }}
      ghcr: true
      ghcr_username: ${{ github.repository_owner }}
      dockerhub_username: mbround18
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
