name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  enforce-label:
    uses: mbround18/gh-reusable/.github/workflows/enforce-labels.yaml@main
    with:
      required_labels_any: "major,minor,patch,internal,performance,question,release,tests,wontfix,documentation,bug,dependencies"
      required_labels_any_description: "Select at least one label ['major','minor','patch', 'documentation']"
      banned_labels: "banned"
    secrets:
      DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
