name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  tagger:
    uses: mbround18/gh-reusable/.github/workflows/tagger.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  binary-release:
    needs: tagger
    uses: mbround18/gh-reusable/.github/workflows/rust-binary-release.yaml@main
    with:
      binary_paths_csv: target/release/odin,target/release/huginn
      build_command: make release PROFILE=production
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
